_target_: src.models.audioslot_module.AudioSlotModule

name: "audio_slot"

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 2e-4

# scheduler:
#   scheduler:
#     _target_: torch.optim.lr_scheduler.LambdaLR
#     _partial_: true
#   warmup_steps: 20
#   decay_steps: 387
#   decay_rate: 0.5


# 1에폭 : 50800,
# 논문에서 1step 64 2500 warmup, 300k step
# 
# scheduler:
#   scheduler:
#     _target_: src.utils.schedular.CosineAnnealingWarmUpRestarts
#     _partial_: true
#     T_0 : 300 #300
#     T_mult : 2 # 1
#     T_up : 20
#     gamma : 0.5
#     eta_max : 0.0002
  
scheduler:
  scheduler: 
    _target_: src.utils.schedular.CosineAnnealingWarmUpRestarts
    _partial_: true
    T_0 : 300
    T_mult : 1
    T_up : 20
    gamma : 0.5
    eta_max : 0.0001
  

net:
  _target_: src.models.components.audioSlots.audioslot.AudioSlot
  num_slots : 4
  num_iterations : 2
  num_attn_heads : 1
  slot_dim : 512
  mlp_hid_dim : 1024
  eps : 1e-8
  num_fourier_bases : 16
  input_ft :  [257,65]
  dec_mlp_hid_dim : 256

