_target_: src.models.audioslot_module.AudioSlotModule

name: "audio_slot"

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0


  
scheduler:
  scheduler: 
    _target_: src.utils.schedular.CosineAnnealingWarmUpRestarts
    _partial_: true
    T_0 : 380
    T_mult : 1
    T_up : 5
    gamma : 0.5
    eta_max : 2e-4
  

net:
  _target_: src.models.components.audioSlots.audioslot.AudioSlot
  num_slots : 4
  num_iterations : 2
  num_attn_heads : 1
  slot_dim : 512
  mlp_hid_dim : 1024
  eps : 1e-8
  num_fourier_bases : 16
  input_ft :  [257,65]
  dec_mlp_hid_dim : 256

istft : 
  n_fft : 512
  hop_length : 125
  win_length : 512
  sample_rate : 16000
