_target_: src.models.audioslot_module.AudioSlotModule

name: "audio_slot"

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0002

# scheduler:
#   scheduler:
#     _target_: torch.optim.lr_scheduler.CosineAnnealingLR
#     _partial_: true
#   warmup_steps: 2500
#   T_max: 2500

scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.LambdaLR
    _partial_: true
  warmup_steps: 20
  decay_steps: 200
  decay_rate: 0.5


net:
  _target_: src.models.components.audioSlots.audioslot.AudioSlot
  num_slots : 2
  num_iterations : 7
  num_attn_heads : 1
  slot_dim : 1024
  mlp_hid_dim : 2048
  eps : 1e-8
  num_fourier_bases : 1024
  input_ft :  [257,65]
